# TestGrid Test Configuration Parameters
version: '0.9'
infrastructureConfig:
  iacProvider: TERRAFORM
  infrastructureProvider: SHELL
  containerOrchestrationEngine: K8S
  parameters:
    - JDK : ORACLE_JDK8
  includes:
    - CentOS
    - mysql
    - ORACLE_JDK8
    - OPEN_JDK8
  excludes:
    - UBUNTU
  provisioners:
  - name: ballerina-deployment
    remoteRepository: "git@github.com:manuri/aws-ballerina.git"
    remoteBranch: "master"
    description: creates infrastructure for ballerina scenario tests
    scripts:
      - name: ballerina-deployment
        description: Creates Kubernetes infrastructure for a database and ballerina installed instance.
        type: SHELL
        phase: CREATE
        file: data-integration/provision-infrastructure.sh
      - name: destroy
        file: data-integration/destroy-cluster.sh
        type: SHELL
        phase: DESTROY
scenarioConfigs:
- testType: JMETER
  remoteRepository: "https://github.com/ballerina-platform/ballerina-lang.git"
  remoteBranch: "ballerina-scenarios"
  name: "ballerina-scenarios"
  description: "ballerina-scenarios"
  file: product-scenarios/test-data.sh
deploymentConfig:
  deploymentPatterns:
    - name: 'scenario tests'
      description: 'dummy'
      remoteRepository: "https://github.com/ballerina-platform/ballerina-lang.git"
      remoteBranch: "ballerina-scenarios"
      dir: .
      scripts:
        - name: 'default'
          type: SHELL
          file: product-scenarios/deployment-data.sh